# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TravLord_Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TravLegendsWarLord(object):
    def setupUi(self, TravLegendsWarLord):
        TravLegendsWarLord.setObjectName("TravLegendsWarLord")
        TravLegendsWarLord.setEnabled(True)
        TravLegendsWarLord.resize(749, 667)
        TravLegendsWarLord.setMinimumSize(QtCore.QSize(500, 500))
        TravLegendsWarLord.setWindowOpacity(100.0)
        TravLegendsWarLord.setStyleSheet("background-image: url(login.png);")

        self.centralwidget = QtWidgets.QWidget(TravLegendsWarLord)
        self.centralwidget.setObjectName("centralwidget")
        self.labelEmail = QtWidgets.QLabel(self.centralwidget)
        self.labelEmail.setGeometry(QtCore.QRect(240, 100, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelEmail.setFont(font)
        self.labelEmail.setStyleSheet("color: rgb(0, 255, 255);")
        self.labelEmail.setFrameShape(QtWidgets.QFrame.Box)
        self.labelEmail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelEmail.setObjectName("labelEmail")

        self.labelPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPassword.setGeometry(QtCore.QRect(320, 210, 91, 41))

        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPassword.setFont(font)
        self.labelPassword.setFrameShape(QtWidgets.QFrame.Box)
        self.labelPassword.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelPassword.setObjectName("labelPassword")

        self.inputemail = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputemail.setGeometry(QtCore.QRect(270, 170, 191, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputemail.sizePolicy().hasHeightForWidth())
        
        self.inputemail.setSizePolicy(sizePolicy)
        self.inputemail.setSizeIncrement(QtCore.QSize(10, 10))
        self.inputemail.setLineWidth(2)
        self.inputemail.setObjectName("inputemail")

        self.inputpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.inputpassword.setGeometry(QtCore.QRect(270, 260, 191, 31))
        self.inputpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputpassword.setObjectName("inputpassword")

        self.buttonlogin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonlogin.setGeometry(QtCore.QRect(420, 320, 75, 23))
        self.buttonlogin.setObjectName("buttonlogin")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(250, 320, 91, 17))
        self.checkBox.setObjectName("checkBox")
        self.world = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.world.setGeometry(QtCore.QRect(120, 370, 491, 31))
        self.world.setObjectName("world")
        TravLegendsWarLord.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TravLegendsWarLord)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        TravLegendsWarLord.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TravLegendsWarLord)
        self.statusbar.setObjectName("statusbar")
        TravLegendsWarLord.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(TravLegendsWarLord)
        QtCore.QMetaObject.connectSlotsByName(TravLegendsWarLord)

    def retranslateUi(self, TravLegendsWarLord):
        _translate = QtCore.QCoreApplication.translate
        TravLegendsWarLord.setWindowTitle(_translate("TravLegendsWarLord", "MainWindow"))
        self.labelEmail.setText(_translate("TravLegendsWarLord", "Account name or e-mail address :"))
        self.labelPassword.setText(_translate("TravLegendsWarLord", "Password :"))
        self.buttonlogin.setText(_translate("TravLegendsWarLord", "login"))
        self.checkBox.setText(_translate("TravLegendsWarLord", "remember me"))
        self.menufile.setTitle(_translate("TravLegendsWarLord", "file"))
import image_rc
